name: Bump all packages (fast)
on:
  workflow_dispatch:
    inputs:
      bumpNumber:
        description: Increase for each bump in the same day
        required: false
        type: number

permissions:
  contents: write
  pull-requests: write

# It's better for it to conflict with other builds and bumps
concurrency:
  group: nyx-main-build
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: nyxbuilder
    timeout-minutes: 1440
    steps:
      # identical to build.yml
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            sandbox-fallback = false
            system-features = big-parallel gccarch-x86-64-v3
          install_options: --daemon
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Configure sandboxing
        run: |
          sed -i -e '/^build-users-group =/d' -e 's/max-jobs =.*/max-jobs = 8/g' /etc/nix/nix.conf
          nix eval ./maintenance#_dev.nixConfig --json | jq -r 'to_entries[] | "\(.key) = \(.value | join(" "))"' >> /etc/nix/nix.conf
      # config to commit
      - name: Bat-signal
        run: |
          set -e
          git config --global user.name 'Chaotic Github Actions'
          git config --global user.email 'actions@chaotic.cx'
      # the bump itself
      - name: Wiggle, wiggle, wiggle
        id: build
        run: nix develop --impure ./maintenance#updater -c 'chaotic-nyx-bumper'
        env:
          NYX_SOURCE: ${{ github.workspace }}
          GH_TOKEN: ${{ github.token }}
          NYX_BUMPN: ${{ inputs.bumpNumber }}
          NYX_BUMP_REVERT: 0
