name: Bump all packages
on:
  schedule:
    - cron: '15 10 * * *'
  workflow_dispatch:
    inputs:
      bumpNumber:
        description: Increase for each bump in the same day
        required: false
        type: number

permissions:
  contents: write
  pull-requests: write

# It's better for it to conflict with other builds and bumps
concurrency:
  group: nyx-main-bump
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: nyxbuilder
    timeout-minutes: 1440
    steps:
      - name: Install Nix
        if: steps.check.outputs.cached != 'true'
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "accept-flake-config = true"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bat-signal
        run: |
          set -e
          git config --global user.name 'Chaotic Github Actions'
          git config --global user.email 'actions@chaotic.cx'
      - name: Wiggle, wiggle, wiggle
        run: nix develop --impure .#updater -c 'chaotic-nyx-bumper'
        env:
          GH_TOKEN: ${{ github.token }}
          BUMPN: ${{ inputs.bumpNumber }}
