name: Bump all packages
on:
  schedule:
    - cron: '15 10 * * *'
  workflow_dispatch:
    inputs:
      bumpNumber:
        description: Increase for each bump in the same day
        required: false
        type: number

permissions:
  contents: write
  pull-requests: write

# It's better for it to conflict with other builds and bumps
concurrency:
  group: nyx-main-build
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: nyxbuilder
    timeout-minutes: 1440
    steps:
      # identical to build.yml
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            accept-flake-config = true
            sandbox-fallback = false
            system-features = gccarch-x86-64-v3
          install_options: --daemon
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install
      - name: Configure sandboxing
        run: |
          sed -i -e '/^build-users-group =/d' -e 's/max-jobs =.*/max-jobs = 8/g' /etc/nix/nix.conf
          nix eval .#_dev.nixConfig --json | jq -r 'to_entries[] | "\(.key) = \(.value | join(" "))"' >> /etc/nix/nix.conf
      # the bump itself
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bat-signal
        run: |
          set -e
          git config --global user.name 'Chaotic Github Actions'
          git config --global user.email 'actions@chaotic.cx'
      - name: Wiggle, wiggle, wiggle
        run: nix develop --impure .#updater -c 'chaotic-nyx-bumper'
        env:
          GH_TOKEN: ${{ github.token }}
          NYX_BUMPN: ${{ inputs.bumpNumber }}
      # similar to build.yml
      - name: Cache
        if: success()
        id: build
        run: nix develop -c chaotic-nyx-build || [ $? -eq 42 ]
        env:
          NYX_WD: ${{ runner.temp }}
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
